# Generated by Django 3.0.3 on 2020-02-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeedetails', '0004_auto_20200219_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='mobile',
            field=models.BigIntegerField(),
        ),
    ]
