# Generated by Django 3.0.3 on 2020-02-20 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employeedetails', '0005_auto_20200219_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='empcode',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='employee',
            name='fullname',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobile',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='employeedetails.Position'),
        ),
    ]
